### ISSUE TITLE
`desc.backend` import order

### ISSUE THREAD

**Issue by ddudt** [PlasmaControl/DESC#453]
If I try to import something from `desc.backend` as my first DESC import statement, I get the following error: 
```
>>> from desc.backend import *
2023-03-13 15:01:08.528019: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
DESC version 0.8.0+4.gdf15db5e,using JAX backend, jax version=0.4.2, jaxlib version=0.4.2, dtype=float64
Using device: CPU, with 307.64 GB available memory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ddudt/DESC/desc/backend.py", line 74, in <module>
    from jax.scipy.linalg import block_diag, cho_factor, cho_solve, qr, solve_triangular
  File "/home/ddudt/.conda/envs/desc-env/lib/python3.10/site-packages/jax/scipy/linalg.py", line 18, in <module>
    from jax._src.scipy.linalg import (
  File "/home/ddudt/.conda/envs/desc-env/lib/python3.10/site-packages/jax/_src/scipy/linalg.py", line 19, in <module>
    import scipy.linalg
  File "/home/ddudt/.conda/envs/desc-env/lib/python3.10/site-packages/scipy/linalg/__init__.py", line 209, in <module>
    from ._matfuncs import *
  File "/home/ddudt/.conda/envs/desc-env/lib/python3.10/site-packages/scipy/linalg/_matfuncs.py", line 19, in <module>
    from ._matfuncs_sqrtm import sqrtm
  File "/home/ddudt/.conda/envs/desc-env/lib/python3.10/site-packages/scipy/linalg/_matfuncs_sqrtm.py", line 24, in <module>
    from ._matfuncs_sqrtm_triu import within_block_loop
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/ddudt/.conda/envs/desc-env/lib/python3.10/site-packages/scipy/linalg/_matfuncs_sqrtm_triu.cpython-310-x86_64-linux-gnu.so)
```

However, it works fine if I import something else from the DESC package first. For example: 
```
>>> from desc.equilibrium import Equilibrium
2023-03-13 15:01:57.219688: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
DESC version 0.8.0+4.gdf15db5e,using JAX backend, jax version=0.4.2, jaxlib version=0.4.2, dtype=float64
Using device: CPU, with 307.69 GB available memory
>>> from desc.backend import *
>>>
```

This is not necessarily an issue that has to be fixed, but I wanted to at least document the behavior and workaround solution.

**Comment by dpanici** [comment]
works for me on WSL2, scipy version `1.9.1`

**Comment by f0uriest** [comment]
Works fine for me with `scipy 1.10.0`, `jax 0.4.1`, `jaxlib 0.4.1`
